# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# NOTE! THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN!
#
# IF YOU WANT TO MODIFY THIS FILE, YOU SHOULD MODIFY THE TEMPLATE
# `get_provider_info_TEMPLATE.py.jinja2` IN the `dev/breeze/src/airflow_breeze/templates` DIRECTORY


def get_provider_info():
    return {
        "package-name": "apache-airflow-providers-tenki",
        "name": "Tenki Sandbox",
        "description": "`Tenki <https://tenki.sh/>`__ sandbox executor.\n\nRuns each Airflow task inside a dedicated, ephemeral Tenki sandbox (an isolated micro-VM)\nprovisioned through the Tenki sandbox SDK. The scheduler builds a workload and passes it to\nthe ``TenkiExecutor``, which serializes it into a Task SDK command, launches a sandbox that\nruns the same Airflow code as the scheduler, and polls the sandbox until it finishes. This\ngives strong per-task isolation and lets individual tasks request their own image, CPU,\nmemory and environment. The ``TenkiExecutor`` can co-exist with other executors (for example\n``LocalExecutor`` or ``KubernetesExecutor``) in the same Airflow deployment.\n",
        "integrations": [
            {
                "integration-name": "Tenki Sandbox",
                "external-doc-url": "https://tenki.sh/",
                "how-to-guide": ["/docs/apache-airflow-providers-tenki/executors/tenki-executor.rst"],
                "tags": ["software"],
            }
        ],
        "executors": ["airflow.providers.tenki.executors.TenkiExecutor"],
        "hooks": [
            {"integration-name": "Tenki Sandbox", "python-modules": ["airflow.providers.tenki.hooks.tenki"]}
        ],
        "connection-types": [
            {
                "hook-class-name": "airflow.providers.tenki.hooks.tenki.TenkiSandboxHook",
                "connection-type": "tenki",
            }
        ],
        "config": {
            "tenki_executor": {
                "description": "This section only applies if you are using the TenkiExecutor in the\n``[core] executor`` configuration value above.\n",
                "options": {
                    "conn_id": {
                        "description": "The Airflow connection (i.e. credentials) used by the Tenki executor to authenticate\nagainst the Tenki sandbox service. The connection ``password`` holds the API auth token,\n``host`` the API base URL and ``extra`` may carry ``gateway_url`` and ``timeout``. The\n``auth_token`` / ``base_url`` / ``gateway_url`` options below take precedence when set.\n",
                        "version_added": None,
                        "type": "string",
                        "example": None,
                        "default": "tenki_default",
                    },
                    "auth_token": {
                        "description": "API auth token passed to ``tenki_sandbox.Client``. Overrides the ``password`` of the\nconnection referenced by ``conn_id`` when provided. Prefer storing the token in the\nconnection or a secrets backend rather than in plain configuration.\n",
                        "version_added": None,
                        "type": "string",
                        "sensitive": True,
                        "example": None,
                        "default": None,
                    },
                    "base_url": {
                        "description": "Control-plane base URL passed to ``tenki_sandbox.Client``. Overrides the connection\n``host`` when provided. When unset, the SDK default (or ``TENKI_API_ENDPOINT``) is used.\n",
                        "version_added": None,
                        "type": "string",
                        "example": "https://api.tenki.cloud",
                        "default": None,
                    },
                    "gateway_url": {
                        "description": "Data-plane gateway URL passed to ``tenki_sandbox.Client``. Overrides the connection\n``extra['gateway_url']`` when provided.\n",
                        "version_added": None,
                        "type": "string",
                        "example": None,
                        "default": None,
                    },
                    "project_id": {
                        "description": "Tenki project id sandboxes are created under. Required by the service when creating a\nsandbox (it can be found in the Tenki console or from the ``who_am_i`` identity). Can be\noverridden per task via ``executor_config``.\n",
                        "version_added": None,
                        "type": "string",
                        "example": "0197a921-49f5-72b7-abef-0f54430f49ef",
                        "default": None,
                    },
                    "workspace_id": {
                        "description": "Tenki workspace id sandboxes are created under (when not implied by the auth token).\n",
                        "version_added": None,
                        "type": "string",
                        "example": None,
                        "default": None,
                    },
                    "image": {
                        "description": "Default container image each sandbox runs. It must contain the same Airflow\ndistribution and Dag code as the scheduler. Can be overridden per task via\n``executor_config``.\n",
                        "version_added": None,
                        "type": "string",
                        "example": "myregistry/airflow:3.0.0",
                        "default": None,
                    },
                    "cpu_cores": {
                        "description": "Default number of CPU cores requested for each sandbox. Can be overridden per task\nvia ``executor_config``. Under-provisioning may cause the sandbox to be terminated on\nstart; ``2`` cores / ``4096`` MB is a safe baseline.\n",
                        "version_added": None,
                        "type": "integer",
                        "example": "2",
                        "default": None,
                    },
                    "memory_mb": {
                        "description": "Default memory (in MB) requested for each sandbox. Can be overridden per task via\n``executor_config``. Very small values (e.g. ``512``) may cause the sandbox to be\nterminated on start.\n",
                        "version_added": None,
                        "type": "integer",
                        "example": "4096",
                        "default": None,
                    },
                    "disk_size_gb": {
                        "description": "Default disk size (in GB) requested for each sandbox.\n",
                        "version_added": None,
                        "type": "integer",
                        "example": None,
                        "default": None,
                    },
                    "idle_timeout_minutes": {
                        "description": "Idle timeout (in minutes) after which an orphaned sandbox is reclaimed by Tenki. Acts\nas a safety net for sandboxes left behind if the scheduler is killed mid-task.\n",
                        "version_added": None,
                        "type": "integer",
                        "example": "30",
                        "default": None,
                    },
                    "create_sandbox_kwargs": {
                        "description": "A JSON object of extra keyword arguments merged into ``tenki_sandbox.Client.create()``\nfor every task (for example default ``tags`` or ``env``). Task-level ``executor_config``\nis merged last and wins over these values.\n",
                        "version_added": None,
                        "type": "string",
                        "example": '{"tags": ["airflow"]}',
                        "default": None,
                    },
                    "check_health_on_startup": {
                        "description": "Whether to check the health of the Tenki sandbox service when the executor starts.\n",
                        "version_added": None,
                        "type": "boolean",
                        "example": None,
                        "default": "True",
                    },
                    "max_run_sandbox_attempts": {
                        "description": "The maximum number of times the executor should attempt to launch (or relaunch) a\nsandbox for a task before marking it failed.\n",
                        "version_added": None,
                        "type": "integer",
                        "example": None,
                        "default": "3",
                    },
                },
            }
        },
    }
